export const PLATFORM_CONTRACT_VERSION = 'v1' as const;
export type PlatformContractVersion = typeof PLATFORM_CONTRACT_VERSION;

export * from './common/schema.js';
export * from './common/identifiers.js';
export * from './common/time.js';
export * from './common/pagination.js';
export * from './common/query.js';
export * from './common/command.js';
export * from './common/operation.js';
export * from './common/problem-details.js';
export * from './common/section.js';
export * from './common/authorization.js';
export * from './common/navigation.js';
export * from './identity/session.js';
export * from './identity/navigation-context.js';
export * from './identity/register.js';
export * from './identity/login.js';
export * from './identity/password.js';
export * from './identity/email-verification.js';
export * from './identity/invitation.js';
export * from './organization/workspace.js';
export * from './organization/members.js';
export * from './organization/invitations.js';
export * from './organization/settings.js';
export * from './project-governance/create.js';
export * from './project-governance/trash.js';
export * from './credentials/private-tokens.js';
export * from './audit/security-audit.js';
export * from './registry/operations.js';
export * from './registry/manifest.js';
