import type { RouteTargetId } from '../common/navigation.js';
import type { PaginationModel } from '../common/pagination.js';
import type { SchemaDef } from '../common/schema.js';
import { identityGetSessionResponse, OPERATION_ID_SESSION } from '../identity/session.js';
import {
  navigationGetContextResponse,
  OPERATION_ID_NAVIGATION,
} from '../identity/navigation-context.js';
import {
  identityRegisterRequest,
  identityRegisterResponse,
  OPERATION_ID_REGISTER,
} from '../identity/register.js';
import {
  identityLoginRequest,
  identityLoginResponse,
  identityLogoutResponse,
  OPERATION_ID_LOGIN,
  OPERATION_ID_LOGOUT,
} from '../identity/login.js';
import {
  identityChangePasswordRequest,
  identityChangePasswordResponse,
  identityConfirmPasswordResetRequest,
  identityConfirmPasswordResetResponse,
  identityRequestPasswordResetRequest,
  identityRequestPasswordResetResponse,
  OPERATION_ID_CHANGE_PASSWORD,
  OPERATION_ID_CONFIRM_PASSWORD_RESET,
  OPERATION_ID_REQUEST_PASSWORD_RESET,
} from '../identity/password.js';
import {
  identityConfirmEmailVerificationRequest,
  identityConfirmEmailVerificationResponse,
  OPERATION_ID_CONFIRM_EMAIL_VERIFICATION,
} from '../identity/email-verification.js';
import {
  OPERATION_ID_ACCEPT_INVITATION,
  organizationAcceptInvitationRequest,
  organizationAcceptInvitationResponse,
} from '../identity/invitation.js';
import {
  OPERATION_ID_CANCEL_ACCOUNT_DELETION,
  OPERATION_ID_CANCEL_ACCOUNT_DELETION_INTENT_LINK,
  OPERATION_ID_DELETE_ACCOUNT,
  OPERATION_ID_DELETE_ACCOUNT_INTENT_LINK,
  OPERATION_ID_DELETE_ACCOUNT_PREFLIGHT,
  OPERATION_ID_REQUEST_ACCOUNT_DELETION,
  identityCancelAccountDeletionIntentLinkPathParams,
  identityCancelAccountDeletionIntentLinkResponse,
  identityCancelAccountDeletionRequest,
  identityCancelAccountDeletionResponse,
  identityDeleteAccountIntentLinkPathParams,
  identityDeleteAccountIntentLinkResponse,
  identityDeleteAccountPreflightResponse,
  identityDeleteAccountRequest,
  identityDeleteAccountResponse,
  identityRequestAccountDeletionRequest,
  identityRequestAccountDeletionResponse,
} from '../identity/deletion.js';
import {
  OPERATION_ID_LIST_PROJECTS,
  organizationListProjectsRequest,
  organizationListProjectsResponse,
} from '../organization/workspace.js';
import {
  OPERATION_ID_CHANGE_ROLE,
  OPERATION_ID_LIST_MEMBERS,
  OPERATION_ID_REMOVE_MEMBER,
  OPERATION_ID_TRANSFER_OWNERSHIP,
  organizationChangeRolePathParams,
  organizationChangeRoleRequest,
  organizationChangeRoleResponse,
  organizationListMembersRequest,
  organizationListMembersResponse,
  organizationRemoveMemberPathParams,
  organizationRemoveMemberRequest,
  organizationRemoveMemberResponse,
  organizationTransferOwnershipPathParams,
  organizationTransferOwnershipRequest,
  organizationTransferOwnershipResponse,
} from '../organization/members.js';
import {
  OPERATION_ID_INVITE_MEMBER,
  OPERATION_ID_RESEND_INVITATION,
  OPERATION_ID_REVOKE_INVITATION,
  organizationInviteMemberPathParams,
  organizationInviteMemberRequest,
  organizationInviteMemberResponse,
  organizationResendInvitationRequest,
  organizationResendInvitationResponse,
  organizationRevokeInvitationRequest,
  organizationRevokeInvitationResponse,
} from '../organization/invitations.js';
import {
  OPERATION_ID_UPDATE_TIMEZONE,
  organizationUpdateTimezonePathParams,
  organizationUpdateTimezoneRequest,
  organizationUpdateTimezoneResponse,
} from '../organization/settings.js';
import {
  OPERATION_ID_CREATE_PROJECT,
  organizationCreateProjectPathParams,
  organizationCreateProjectRequest,
  organizationCreateProjectResponse,
} from '../project-governance/create.js';
import {
  OPERATION_ID_LIST_TRASH,
  OPERATION_ID_RESTORE_PROJECT,
  projectGovernanceListTrashRequest,
  projectGovernanceListTrashResponse,
  projectGovernanceRestoreProjectPathParams,
  projectGovernanceRestoreProjectRequest,
  projectGovernanceRestoreProjectResponse,
} from '../project-governance/trash.js';
import {
  OPERATION_ID_CREATE_PRIVATE_TOKEN,
  OPERATION_ID_LIST_PRIVATE_TOKENS,
  OPERATION_ID_REVOKE_PRIVATE_TOKEN,
  credentialsCreatePrivateTokenPathParams,
  credentialsCreatePrivateTokenRequest,
  credentialsCreatePrivateTokenResponse,
  credentialsListPrivateTokensRequest,
  credentialsListPrivateTokensResponse,
  credentialsRevokePrivateTokenRequest,
  credentialsRevokePrivateTokenResponse,
} from '../credentials/private-tokens.js';
import {
  OPERATION_ID_LIST_SECURITY_AUDIT,
  auditListSecurityAuditPathParams,
  auditListSecurityAuditQuery,
  auditListSecurityAuditResponse,
} from '../audit/security-audit.js';
import {
  OPERATION_ID_LIST_REQUEST_ENDPOINTS,
  requestsListEndpointsPathParams,
  requestsListEndpointsQuery,
  requestsListEndpointsResponse,
} from '../monitoring/request-metrics.js';
import {
  OPERATION_ID_GET_DATA_STATUS,
  diagnosticsGetDataStatusPathParams,
  diagnosticsGetDataStatusQuery,
  diagnosticsGetDataStatusResponse,
} from '../monitoring/diagnostics.js';
import {
  OPERATION_ID_LIST_PERFORMANCE_PAGES,
  performanceListPagesPathParams,
  performanceListPagesQuery,
  performanceListPagesResponse,
} from '../monitoring/performance.js';
import {
  OPERATION_ID_GET_USAGE_SUMMARY,
  usageGetSummaryPathParams,
  usageGetSummaryResponse,
} from '../usage-and-policy/usage.js';
import {
  OPERATION_ID_GET_ISSUE_DETAIL,
  OPERATION_ID_LIST_ISSUES,
  issuesGetIssueDetailPathParams,
  issuesGetIssueDetailResponse,
  issuesListIssuesPathParams,
  issuesListIssuesQuery,
  issuesListIssuesResponse,
} from '../issues-and-alerts/issue-queries.js';
import {
  OPERATION_ID_BATCH_UPDATE_ISSUES,
  OPERATION_ID_CREATE_ISSUE_NOTE,
  OPERATION_ID_DELETE_ISSUE_NOTE,
  OPERATION_ID_MERGE_ISSUES,
  OPERATION_ID_UPDATE_ISSUE_ASSIGNEE,
  OPERATION_ID_UPDATE_ISSUE_PRIORITY,
  OPERATION_ID_UPDATE_ISSUE_STATE,
  issuesBatchUpdateBody,
  issuesBatchUpdatePathParams,
  issuesBatchUpdateResponse,
  issuesCreateNoteBody,
  issuesCreateNotePathParams,
  issuesCreateNoteResponse,
  issuesDeleteNoteBody,
  issuesDeleteNotePathParams,
  issuesDeleteNoteResponse,
  issuesMergeBody,
  issuesMergePathParams,
  issuesMergeResponse,
  issuesUpdateAssigneeBody,
  issuesUpdateAssigneePathParams,
  issuesUpdateAssigneeResponse,
  issuesUpdatePriorityBody,
  issuesUpdatePriorityPathParams,
  issuesUpdatePriorityResponse,
  issuesUpdateStateBody,
  issuesUpdateStatePathParams,
  issuesUpdateStateResponse,
} from '../issues-and-alerts/issue-commands.js';
import {
  OPERATION_ID_ALERTS_CREATE_RULE,
  OPERATION_ID_ALERTS_GET_CAPABILITY,
  OPERATION_ID_ALERTS_GET_INSTANCE,
  OPERATION_ID_ALERTS_LIST,
  OPERATION_ID_ALERTS_UPDATE_RULE,
  alertsCreateRuleBody,
  alertsCreateRulePathParams,
  alertsCreateRuleResponse,
  alertsGetCapabilityPathParams,
  alertsGetCapabilityResponse,
  alertsGetInstanceDetailPathParams,
  alertsGetInstanceDetailResponse,
  alertsListRulesAndInstancesPathParams,
  alertsListRulesAndInstancesQuery,
  alertsListRulesAndInstancesResponse,
  alertsUpdateRuleBody,
  alertsUpdateRulePathParams,
  alertsUpdateRuleResponse,
} from '../issues-and-alerts/alerts.js';
import {
  OPERATION_ID_RELEASES_LIST,
  OPERATION_ID_SOURCE_MAPS_LIST,
  OPERATION_ID_SOURCE_MAPS_REPARSE,
  OPERATION_ID_SOURCE_MAPS_REPLACE,
  OPERATION_ID_SOURCE_MAPS_UPLOAD,
  releasesListReleasesPathParams,
  releasesListReleasesResponse,
  sourceMapsListFilesPathParams,
  sourceMapsListFilesResponse,
  sourceMapsReparseBody,
  sourceMapsReparsePathParams,
  sourceMapsReparseResponse,
  sourceMapsReplaceBody,
  sourceMapsReplacePathParams,
  sourceMapsReplaceResponse,
  sourceMapsUploadBody,
  sourceMapsUploadPathParams,
  sourceMapsUploadResponse,
} from '../releases/releases.js';
import {
  OPERATION_ID_ACCESS_CHANGE_ROLE,
  OPERATION_ID_ACCESS_GRANT,
  OPERATION_ID_ACCESS_LIST,
  OPERATION_ID_ACCESS_REMOVE,
  accessChangeProjectRoleBody,
  accessChangeProjectRolePathParams,
  accessChangeProjectRoleResponse,
  accessGrantProjectMembershipBody,
  accessGrantProjectMembershipPathParams,
  accessGrantProjectMembershipResponse,
  accessListEffectiveMembersPathParams,
  accessListEffectiveMembersResponse,
  accessRemoveProjectMembershipBody,
  accessRemoveProjectMembershipPathParams,
  accessRemoveProjectMembershipResponse,
} from '../project-governance/access.js';
import {
  OPERATION_ID_SETTINGS_CREATE_ENVIRONMENT,
  OPERATION_ID_SETTINGS_GET,
  OPERATION_ID_SETTINGS_LIST_ENVIRONMENTS,
  OPERATION_ID_SETTINGS_UPDATE,
  settingsCreateEnvironmentBody,
  settingsCreateEnvironmentPathParams,
  settingsCreateEnvironmentResponse,
  settingsGetProjectPathParams,
  settingsGetProjectResponse,
  settingsListEnvironmentsPathParams,
  settingsListEnvironmentsResponse,
  settingsUpdateProjectBody,
  settingsUpdateProjectPathParams,
  settingsUpdateProjectResponse,
} from '../project-governance/settings.js';
import {
  OPERATION_ID_LIFECYCLE_ARCHIVE,
  OPERATION_ID_LIFECYCLE_MOVE_TO_TRASH,
  OPERATION_ID_LIFECYCLE_RESTORE,
  lifecycleArchiveProjectBody,
  lifecycleArchiveProjectPathParams,
  lifecycleArchiveProjectResponse,
  lifecycleMoveToTrashBody,
  lifecycleMoveToTrashPathParams,
  lifecycleMoveToTrashResponse,
  lifecycleRestoreProjectBody,
  lifecycleRestoreProjectPathParams,
  lifecycleRestoreProjectResponse,
} from '../project-governance/lifecycle.js';
import {
  OPERATION_ID_CREDENTIALS_CREATE,
  OPERATION_ID_CREDENTIALS_DISABLE,
  OPERATION_ID_CREDENTIALS_ENABLE,
  OPERATION_ID_CREDENTIALS_LIST,
  OPERATION_ID_CREDENTIALS_REVOKE,
  credentialsCreateClientKeyBody,
  credentialsCreateClientKeyPathParams,
  credentialsCreateClientKeyResponse,
  credentialsDisableClientKeyBody,
  credentialsDisableClientKeyPathParams,
  credentialsDisableClientKeyResponse,
  credentialsEnableClientKeyBody,
  credentialsEnableClientKeyPathParams,
  credentialsEnableClientKeyResponse,
  credentialsListClientKeysPathParams,
  credentialsListClientKeysResponse,
  credentialsRevokeClientKeyBody,
  credentialsRevokeClientKeyPathParams,
  credentialsRevokeClientKeyResponse,
} from '../credentials/client-keys.js';

export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE';
export type AuthLevel = 'public' | 'intent' | 'session' | 'recent-verification';

export interface OperationDef {
  readonly operationId: string;
  readonly domain: string;
  readonly authLevel: AuthLevel;
  readonly method: HttpMethod;
  readonly path: string;
  readonly summary: string;
  readonly request?: {
    readonly pathParams?: SchemaDef;
    readonly query?: SchemaDef;
    readonly body?: SchemaDef;
    readonly idempotency?: boolean;
    readonly csrf?: boolean;
    readonly versioned?: boolean;
  };
  readonly responses: Readonly<Record<number, SchemaDef>>;
  readonly errorCodes: readonly string[];
  readonly page?: RouteTargetId;
  readonly pagination?: PaginationModel;
  readonly tags: readonly string[];
}

export const PLATFORM_OPERATIONS: readonly OperationDef[] = [
  {
    operationId: OPERATION_ID_SESSION,
    domain: 'identity',
    authLevel: 'public',
    method: 'GET',
    path: '/api/platform/v1/session',
    summary: 'Resolve the current account session projection and CSRF token',
    responses: { 200: identityGetSessionResponse },
    errorCodes: ['authentication', 'authority_unavailable'],
    page: 'workspace.home',
    tags: ['identity', 'session'],
  },
  {
    operationId: OPERATION_ID_NAVIGATION,
    domain: 'identity',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/navigation/context',
    summary: 'Resolve the authorized navigation context for the current scope',
    responses: { 200: navigationGetContextResponse },
    errorCodes: ['authentication', 'authorization', 'authority_unavailable'],
    page: 'workspace.home',
    tags: ['identity', 'navigation'],
  },
  {
    operationId: OPERATION_ID_REGISTER,
    domain: 'identity',
    authLevel: 'public',
    method: 'POST',
    path: '/api/platform/v1/auth/register',
    summary: 'Register a new account and create the personal workspace',
    request: { body: identityRegisterRequest, idempotency: true, csrf: false },
    responses: { 200: identityRegisterResponse },
    errorCodes: [
      'structural_error',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.register',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CONFIRM_EMAIL_VERIFICATION,
    domain: 'identity',
    authLevel: 'intent',
    method: 'POST',
    path: '/api/platform/v1/auth/email/confirm',
    summary: 'Confirm a pending email verification intent (intent cookie + CSRF)',
    request: { body: identityConfirmEmailVerificationRequest, idempotency: true, csrf: true },
    responses: { 200: identityConfirmEmailVerificationResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.verify-email-confirm',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_LOGIN,
    domain: 'identity',
    authLevel: 'public',
    method: 'POST',
    path: '/api/platform/v1/auth/login',
    summary: 'Authenticate an account and establish a session',
    request: { body: identityLoginRequest, idempotency: true, csrf: false },
    responses: { 200: identityLoginResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.login',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_LOGOUT,
    domain: 'identity',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/auth/logout',
    summary: 'Revoke the current session and sign out',
    request: { idempotency: false, csrf: true },
    responses: { 200: identityLogoutResponse },
    errorCodes: ['authentication', 'authorization', 'authority_unavailable'],
    page: 'auth.login',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_REQUEST_PASSWORD_RESET,
    domain: 'identity',
    authLevel: 'public',
    method: 'POST',
    path: '/api/platform/v1/auth/password/request',
    summary: 'Request a password reset email (enumeration-safe)',
    request: { body: identityRequestPasswordResetRequest, idempotency: true, csrf: false },
    responses: { 200: identityRequestPasswordResetResponse },
    errorCodes: [
      'structural_error',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.forgot-password',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CONFIRM_PASSWORD_RESET,
    domain: 'identity',
    authLevel: 'intent',
    method: 'POST',
    path: '/api/platform/v1/auth/password/confirm',
    summary: 'Confirm a password reset intent and set a new password',
    request: { body: identityConfirmPasswordResetRequest, idempotency: true, csrf: true },
    responses: { 200: identityConfirmPasswordResetResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.reset-password',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CHANGE_PASSWORD,
    domain: 'identity',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/auth/password/change',
    summary: 'Change the current password and revoke all sessions',
    request: { body: identityChangePasswordRequest, idempotency: true, csrf: true },
    responses: { 200: identityChangePasswordResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_DELETE_ACCOUNT_PREFLIGHT,
    domain: 'identity',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/account/deletion/preflight',
    summary: 'Resolve the account deletion preflight projection (unique-owner blockers)',
    request: { csrf: false, idempotency: false },
    responses: { 200: identityDeleteAccountPreflightResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'authority_unavailable'],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_REQUEST_ACCOUNT_DELETION,
    domain: 'identity',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/account/deletion/request',
    summary: 'Send the account deletion confirmation email (creates the deletion_request intent)',
    request: { body: identityRequestAccountDeletionRequest, idempotency: true, csrf: true },
    responses: { 200: identityRequestAccountDeletionResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'state_machine_conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_DELETE_ACCOUNT_INTENT_LINK,
    domain: 'identity',
    authLevel: 'public',
    method: 'GET',
    path: '/api/platform/v1/account/deletion/intent/:token',
    summary: 'Validate the account deletion confirmation link and establish the intent cookie',
    request: {
      pathParams: identityDeleteAccountIntentLinkPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: identityDeleteAccountIntentLinkResponse },
    errorCodes: ['not_found', 'business_validation', 'authority_unavailable'],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_DELETE_ACCOUNT,
    domain: 'identity',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/account/deletion',
    summary: 'Request account deletion (dual verification + final unique-owner recheck)',
    request: { body: identityDeleteAccountRequest, idempotency: true, csrf: true },
    responses: { 200: identityDeleteAccountResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'state_machine_conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CANCEL_ACCOUNT_DELETION_INTENT_LINK,
    domain: 'identity',
    authLevel: 'public',
    method: 'GET',
    path: '/api/platform/v1/account/deletion/cancel/intent/:token',
    summary: 'Validate the deletion cancellation link and establish the intent cookie',
    request: {
      pathParams: identityCancelAccountDeletionIntentLinkPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: identityCancelAccountDeletionIntentLinkResponse },
    errorCodes: ['not_found', 'business_validation', 'authority_unavailable'],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CANCEL_ACCOUNT_DELETION,
    domain: 'identity',
    authLevel: 'intent',
    method: 'POST',
    path: '/api/platform/v1/account/deletion/cancel',
    summary: 'Cancel an account deletion within the cooling window (intent cookie + CSRF)',
    request: { body: identityCancelAccountDeletionRequest, idempotency: true, csrf: true },
    responses: { 200: identityCancelAccountDeletionResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'state_machine_conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_ACCEPT_INVITATION,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/invitations/accept',
    summary: 'Accept an organization invitation atomically (intent cookie + CSRF)',
    request: { body: organizationAcceptInvitationRequest, idempotency: true, csrf: true },
    responses: { 200: organizationAcceptInvitationResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'invitation.accept',
    tags: ['organization', 'invitation'],
  },
  {
    operationId: OPERATION_ID_LIST_PROJECTS,
    domain: 'organization',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects',
    summary: 'List projects visible to the current account in an organization',
    request: { pathParams: organizationListProjectsRequest, csrf: false, idempotency: false },
    responses: { 200: organizationListProjectsResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'workspace.home',
    tags: ['organization', 'workspace'],
  },
  {
    operationId: OPERATION_ID_CREATE_PROJECT,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects',
    summary: 'Atomically create a project with default environment and client key (owner/admin)',
    request: {
      pathParams: organizationCreateProjectPathParams,
      body: organizationCreateProjectRequest,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: organizationCreateProjectResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.project-create',
    tags: ['project-governance', 'workspace'],
  },
  {
    operationId: OPERATION_ID_LIST_MEMBERS,
    domain: 'organization',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/members',
    summary: 'List organization members with masked emails',
    request: { pathParams: organizationListMembersRequest, csrf: false, idempotency: false },
    responses: { 200: organizationListMembersResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'members'],
  },
  {
    operationId: OPERATION_ID_INVITE_MEMBER,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/invitations',
    summary: 'Invite a member to an organization (atomic invite + audit)',
    request: {
      pathParams: organizationInviteMemberPathParams,
      body: organizationInviteMemberRequest,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: organizationInviteMemberResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'invitation'],
  },
  {
    operationId: OPERATION_ID_REVOKE_INVITATION,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/invitations/:invitationId/revoke',
    summary: 'Revoke a pending organization invitation',
    request: {
      pathParams: organizationRevokeInvitationRequest,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationRevokeInvitationResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'invitation'],
  },
  {
    operationId: OPERATION_ID_RESEND_INVITATION,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/invitations/:invitationId/resend',
    summary: 'Resend a pending organization invitation email',
    request: {
      pathParams: organizationResendInvitationRequest,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationResendInvitationResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'invitation'],
  },
  {
    operationId: OPERATION_ID_CHANGE_ROLE,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/members/:accountId/role',
    summary: 'Change an organization member role (never to/from owner)',
    request: {
      pathParams: organizationChangeRolePathParams,
      body: organizationChangeRoleRequest,
      versioned: true,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationChangeRoleResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'version_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'members'],
  },
  {
    operationId: OPERATION_ID_REMOVE_MEMBER,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/members/:accountId/remove',
    summary: 'Remove a member from an organization (never the last owner)',
    request: {
      pathParams: organizationRemoveMemberPathParams,
      body: organizationRemoveMemberRequest,
      versioned: true,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationRemoveMemberResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'version_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'members'],
  },
  {
    operationId: OPERATION_ID_TRANSFER_OWNERSHIP,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/ownership',
    summary: 'Transfer organization ownership atomically (owner invariant)',
    request: {
      pathParams: organizationTransferOwnershipPathParams,
      body: organizationTransferOwnershipRequest,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: organizationTransferOwnershipResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'members'],
  },
  {
    operationId: OPERATION_ID_UPDATE_TIMEZONE,
    domain: 'organization',
    authLevel: 'session',
    method: 'PATCH',
    path: '/api/platform/v1/organizations/:organizationId/settings/timezone',
    summary: 'Update the organization business timezone (versioned)',
    request: {
      pathParams: organizationUpdateTimezonePathParams,
      body: organizationUpdateTimezoneRequest,
      versioned: true,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationUpdateTimezoneResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'version_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.settings',
    tags: ['organization', 'settings'],
  },
  {
    operationId: OPERATION_ID_LIST_TRASH,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/trash',
    summary: 'List recoverable trashed projects (owner/admin)',
    request: { pathParams: projectGovernanceListTrashRequest, csrf: false, idempotency: false },
    responses: { 200: projectGovernanceListTrashResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.trash',
    tags: ['project-governance', 'trash'],
  },
  {
    operationId: OPERATION_ID_RESTORE_PROJECT,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/trash/:projectId/restore',
    summary: 'Restore a trashed project within the recovery window (G10 safety rules)',
    request: {
      pathParams: projectGovernanceRestoreProjectPathParams,
      body: projectGovernanceRestoreProjectRequest,
      versioned: true,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: projectGovernanceRestoreProjectResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'state_machine_conflict',
      'idempotency_conflict',
      'version_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.trash',
    tags: ['project-governance', 'trash'],
  },
  {
    operationId: OPERATION_ID_LIST_PRIVATE_TOKENS,
    domain: 'credentials',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/private-tokens',
    summary: 'List private management tokens (metadata only, no secret)',
    request: { pathParams: credentialsListPrivateTokensRequest, csrf: false, idempotency: false },
    responses: { 200: credentialsListPrivateTokensResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.tokens',
    tags: ['credentials', 'tokens'],
  },
  {
    operationId: OPERATION_ID_CREATE_PRIVATE_TOKEN,
    domain: 'credentials',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/private-tokens',
    summary: 'Create a private management token (one-time plaintext delivery)',
    request: {
      pathParams: credentialsCreatePrivateTokenPathParams,
      body: credentialsCreatePrivateTokenRequest,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: credentialsCreatePrivateTokenResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.tokens',
    tags: ['credentials', 'tokens'],
  },
  {
    operationId: OPERATION_ID_REVOKE_PRIVATE_TOKEN,
    domain: 'credentials',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/private-tokens/:tokenId/revoke',
    summary: 'Irreversibly revoke a private management token',
    request: {
      pathParams: credentialsRevokePrivateTokenRequest,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: credentialsRevokePrivateTokenResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.tokens',
    tags: ['credentials', 'tokens'],
  },
  {
    operationId: OPERATION_ID_LIST_SECURITY_AUDIT,
    domain: 'audit',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/audit',
    summary: 'List the security audit timeline (redacted summaries)',
    request: {
      pathParams: auditListSecurityAuditPathParams,
      query: auditListSecurityAuditQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: auditListSecurityAuditResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.audit',
    tags: ['audit', 'security'],
  },
  {
    operationId: OPERATION_ID_LIST_REQUEST_ENDPOINTS,
    domain: 'monitoring-projections',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/requests',
    summary: 'List request endpoint metric projections for a project time window',
    request: {
      pathParams: requestsListEndpointsPathParams,
      query: requestsListEndpointsQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: requestsListEndpointsResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.requests',
    tags: ['monitoring', 'requests'],
  },
  {
    operationId: OPERATION_ID_GET_DATA_STATUS,
    domain: 'monitoring-projections',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/data-status',
    summary:
      'Resolve the ingestion data-status diagnosis projection for a project (safe summaries)',
    request: {
      pathParams: diagnosticsGetDataStatusPathParams,
      query: diagnosticsGetDataStatusQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: diagnosticsGetDataStatusResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.data-status',
    tags: ['monitoring', 'diagnostics'],
  },
  {
    operationId: OPERATION_ID_LIST_PERFORMANCE_PAGES,
    domain: 'monitoring-projections',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/performance',
    summary:
      'List performance metric projections for a project time window (LCP/INP/CLS/page-load)',
    request: {
      pathParams: performanceListPagesPathParams,
      query: performanceListPagesQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: performanceListPagesResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.performance',
    tags: ['monitoring', 'performance'],
  },
  {
    operationId: OPERATION_ID_GET_USAGE_SUMMARY,
    domain: 'usage-and-policy',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/usage',
    summary:
      'Resolve the organization periodic resource usage and degradation stage (PRD §15) from real processed data',
    request: {
      pathParams: usageGetSummaryPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: usageGetSummaryResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.usage',
    tags: ['usage-and-policy'],
  },
  {
    operationId: OPERATION_ID_UPDATE_ISSUE_STATE,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues/:issueId/state',
    summary: 'Transition an Issue lifecycle state (PRD §10.1—§10.5) with optimistic version',
    request: {
      pathParams: issuesUpdateStatePathParams,
      body: issuesUpdateStateBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: issuesUpdateStateResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issue-detail',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_UPDATE_ISSUE_ASSIGNEE,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues/:issueId/assignee',
    summary: 'Assign, transfer, or clear the Issue assignee (PRD §10.2)',
    request: {
      pathParams: issuesUpdateAssigneePathParams,
      body: issuesUpdateAssigneeBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: issuesUpdateAssigneeResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'conflict',
      'idempotency_conflict',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issue-detail',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_UPDATE_ISSUE_PRIORITY,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues/:issueId/priority',
    summary: 'Set or clear the Issue priority (PRD §10.3)',
    request: {
      pathParams: issuesUpdatePriorityPathParams,
      body: issuesUpdatePriorityBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: issuesUpdatePriorityResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issue-detail',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_CREATE_ISSUE_NOTE,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues/:issueId/notes',
    summary: 'Add a member note to an Issue (PRD §10.6)',
    request: {
      pathParams: issuesCreateNotePathParams,
      body: issuesCreateNoteBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: issuesCreateNoteResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issue-detail',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_DELETE_ISSUE_NOTE,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues/:issueId/notes/:noteId/delete',
    summary: 'Soft-delete a member note (author or admin for sensitive content, PRD §10.6)',
    request: {
      pathParams: issuesDeleteNotePathParams,
      body: issuesDeleteNoteBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: issuesDeleteNoteResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'idempotency_conflict',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issue-detail',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_MERGE_ISSUES,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues/:issueId/merge',
    summary: 'Merge an Issue into a primary Issue (PRD §9.7)',
    request: {
      pathParams: issuesMergePathParams,
      body: issuesMergeBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: issuesMergeResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issue-detail',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_BATCH_UPDATE_ISSUES,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues/batch',
    summary: 'Page-scoped batch Issue update (≤100 items, PRD §10.7)',
    request: {
      pathParams: issuesBatchUpdatePathParams,
      body: issuesBatchUpdateBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: issuesBatchUpdateResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issues',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_LIST_ISSUES,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues',
    summary: 'List Issue aggregates for a project with pagination and filters',
    request: {
      pathParams: issuesListIssuesPathParams,
      query: issuesListIssuesQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: issuesListIssuesResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issues',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_GET_ISSUE_DETAIL,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/issues/:issueId',
    summary: 'Resolve an Issue detail with bounded samples and activity/notes projection',
    request: {
      pathParams: issuesGetIssueDetailPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: issuesGetIssueDetailResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.issue-detail',
    tags: ['issues-and-alerts'],
  },
  {
    operationId: OPERATION_ID_ALERTS_GET_CAPABILITY,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/alerts/capability',
    summary:
      'Resolve the alert rule capability contract, fixed options, filter dimension availability and eligible recipients (C11)',
    request: {
      pathParams: alertsGetCapabilityPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: alertsGetCapabilityResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.alerts',
    tags: ['issues-and-alerts', 'alerts'],
  },
  {
    operationId: OPERATION_ID_ALERTS_LIST,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/alerts',
    summary: 'List alert rules with their current evaluation projection and alert instances (C10)',
    request: {
      pathParams: alertsListRulesAndInstancesPathParams,
      query: alertsListRulesAndInstancesQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: alertsListRulesAndInstancesResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.alerts',
    tags: ['issues-and-alerts', 'alerts'],
  },
  {
    operationId: OPERATION_ID_ALERTS_CREATE_RULE,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/alerts/rules',
    summary: 'Create an alert rule (project admin, PRD §11.2)',
    request: {
      pathParams: alertsCreateRulePathParams,
      body: alertsCreateRuleBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: alertsCreateRuleResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.alert-rule-create',
    tags: ['issues-and-alerts', 'alerts'],
  },
  {
    operationId: OPERATION_ID_ALERTS_UPDATE_RULE,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/alerts/rules/:ruleId',
    summary: 'Update an alert rule (project admin, optimistic version, PRD §11.2)',
    request: {
      pathParams: alertsUpdateRulePathParams,
      body: alertsUpdateRuleBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: alertsUpdateRuleResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'version_conflict',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.alert-rule-edit',
    tags: ['issues-and-alerts', 'alerts'],
  },
  {
    operationId: OPERATION_ID_ALERTS_GET_INSTANCE,
    domain: 'issues-and-alerts',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/alerts/instances/:instanceId',
    summary:
      'Resolve an alert instance detail with its rule snapshot, evaluation evidence and business transition timeline (C12)',
    request: {
      pathParams: alertsGetInstanceDetailPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: alertsGetInstanceDetailResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.alert-instance-detail',
    tags: ['issues-and-alerts', 'alerts'],
  },
  {
    operationId: OPERATION_ID_RELEASES_LIST,
    domain: 'releases',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/releases',
    summary: 'List release identities for a project (C8)',
    request: {
      pathParams: releasesListReleasesPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: releasesListReleasesResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.releases',
    tags: ['releases'],
  },
  {
    operationId: OPERATION_ID_SOURCE_MAPS_LIST,
    domain: 'releases',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/releases/:releaseId/source-maps',
    summary: 'List current effective Source Map files for a release (C9)',
    request: {
      pathParams: sourceMapsListFilesPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: sourceMapsListFilesResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.source-maps',
    tags: ['releases', 'source-maps'],
  },
  {
    operationId: OPERATION_ID_SOURCE_MAPS_UPLOAD,
    domain: 'releases',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/source-maps',
    summary:
      'Upload a Source Map for a release build path (idempotent digest; replace requires explicit confirmation)',
    request: {
      pathParams: sourceMapsUploadPathParams,
      body: sourceMapsUploadBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: sourceMapsUploadResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.source-maps',
    tags: ['releases', 'source-maps'],
  },
  {
    operationId: OPERATION_ID_SOURCE_MAPS_REPLACE,
    domain: 'releases',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/releases/:releaseId/source-maps/:sourceMapFileId/replace',
    summary: 'Explicitly replace a Source Map after a digest conflict (versioned, audited)',
    request: {
      pathParams: sourceMapsReplacePathParams,
      body: sourceMapsReplaceBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: sourceMapsReplaceResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'version_conflict',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.source-maps',
    tags: ['releases', 'source-maps'],
  },
  {
    operationId: OPERATION_ID_SOURCE_MAPS_REPARSE,
    domain: 'releases',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/releases/:releaseId/reparse',
    summary: 'Queue a bounded reparse for a release (retry/refresh symbolication, PRD §8.3.8)',
    request: {
      pathParams: sourceMapsReparsePathParams,
      body: sourceMapsReparseBody,
      csrf: true,
      idempotency: true,
    },
    responses: { 200: sourceMapsReparseResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.source-maps',
    tags: ['releases', 'source-maps'],
  },
  {
    operationId: OPERATION_ID_ACCESS_LIST,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/access',
    summary: 'List effective project access for every person (org inheritance + explicit membership)',
    request: { pathParams: accessListEffectiveMembersPathParams, csrf: false, idempotency: false },
    responses: { 200: accessListEffectiveMembersResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'rate_limited', 'authority_unavailable'],
    page: 'project.access',
    tags: ['project-governance', 'access'],
  },
  {
    operationId: OPERATION_ID_ACCESS_GRANT,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/access/members',
    summary: 'Grant a project role to a current organization member (audited)',
    request: { pathParams: accessGrantProjectMembershipPathParams, body: accessGrantProjectMembershipBody, csrf: true, idempotency: true },
    responses: { 200: accessGrantProjectMembershipResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'idempotency_conflict', 'field_validation', 'rate_limited', 'authority_unavailable'],
    page: 'project.access',
    tags: ['project-governance', 'access'],
  },
  {
    operationId: OPERATION_ID_ACCESS_CHANGE_ROLE,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/access/members/:accountId/role',
    summary: 'Change an explicit project member role (audited)',
    request: { pathParams: accessChangeProjectRolePathParams, body: accessChangeProjectRoleBody, csrf: true, idempotency: true },
    responses: { 200: accessChangeProjectRoleResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'idempotency_conflict', 'field_validation', 'rate_limited', 'authority_unavailable'],
    page: 'project.access',
    tags: ['project-governance', 'access'],
  },
  {
    operationId: OPERATION_ID_ACCESS_REMOVE,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/access/members/:accountId/remove',
    summary: 'Remove an explicit project membership (org inheritance may remain; audited)',
    request: { pathParams: accessRemoveProjectMembershipPathParams, body: accessRemoveProjectMembershipBody, csrf: true, idempotency: true },
    responses: { 200: accessRemoveProjectMembershipResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'idempotency_conflict', 'rate_limited', 'authority_unavailable'],
    page: 'project.access',
    tags: ['project-governance', 'access'],
  },
  {
    operationId: OPERATION_ID_CREDENTIALS_LIST,
    domain: 'credentials',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/client-keys',
    summary: 'List client-key metadata (never the secret)',
    request: { pathParams: credentialsListClientKeysPathParams, csrf: false, idempotency: false },
    responses: { 200: credentialsListClientKeysResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'rate_limited', 'authority_unavailable'],
    page: 'project.client-keys',
    tags: ['credentials', 'client-keys'],
  },
  {
    operationId: OPERATION_ID_CREDENTIALS_CREATE,
    domain: 'credentials',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/client-keys',
    summary: 'Create a client key (one-time clientKey delivery, audited)',
    request: { pathParams: credentialsCreateClientKeyPathParams, body: credentialsCreateClientKeyBody, csrf: true, idempotency: true },
    responses: { 200: credentialsCreateClientKeyResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'idempotency_conflict', 'field_validation', 'rate_limited', 'authority_unavailable'],
    page: 'project.client-keys',
    tags: ['credentials', 'client-keys'],
  },
  {
    operationId: OPERATION_ID_CREDENTIALS_DISABLE,
    domain: 'credentials',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/client-keys/:keyId/disable',
    summary: 'Temporarily disable a client key (audited)',
    request: { pathParams: credentialsDisableClientKeyPathParams, body: credentialsDisableClientKeyBody, csrf: true, idempotency: true },
    responses: { 200: credentialsDisableClientKeyResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'idempotency_conflict', 'rate_limited', 'authority_unavailable'],
    page: 'project.client-keys',
    tags: ['credentials', 'client-keys'],
  },
  {
    operationId: OPERATION_ID_CREDENTIALS_ENABLE,
    domain: 'credentials',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/client-keys/:keyId/enable',
    summary: 'Re-enable a disabled client key (audited)',
    request: { pathParams: credentialsEnableClientKeyPathParams, body: credentialsEnableClientKeyBody, csrf: true, idempotency: true },
    responses: { 200: credentialsEnableClientKeyResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'idempotency_conflict', 'rate_limited', 'authority_unavailable'],
    page: 'project.client-keys',
    tags: ['credentials', 'client-keys'],
  },
  {
    operationId: OPERATION_ID_CREDENTIALS_REVOKE,
    domain: 'credentials',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/client-keys/:keyId/revoke',
    summary: 'Irreversibly revoke a client key (audited)',
    request: { pathParams: credentialsRevokeClientKeyPathParams, body: credentialsRevokeClientKeyBody, csrf: true, idempotency: true },
    responses: { 200: credentialsRevokeClientKeyResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'idempotency_conflict', 'rate_limited', 'authority_unavailable'],
    page: 'project.client-keys',
    tags: ['credentials', 'client-keys'],
  },
  {
    operationId: OPERATION_ID_SETTINGS_GET,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/settings',
    summary: 'Resolve project settings and the authoritative lifecycle summary',
    request: { pathParams: settingsGetProjectPathParams, csrf: false, idempotency: false },
    responses: { 200: settingsGetProjectResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'rate_limited', 'authority_unavailable'],
    page: 'project.settings',
    tags: ['project-governance', 'settings'],
  },
  {
    operationId: OPERATION_ID_SETTINGS_UPDATE,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'PATCH',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/settings',
    summary: 'Update editable project settings (name + optional website URL, versioned)',
    request: { pathParams: settingsUpdateProjectPathParams, body: settingsUpdateProjectBody, versioned: true, csrf: true, idempotency: true },
    responses: { 200: settingsUpdateProjectResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'version_conflict', 'idempotency_conflict', 'field_validation', 'rate_limited', 'authority_unavailable'],
    page: 'project.settings',
    tags: ['project-governance', 'settings'],
  },
  {
    operationId: OPERATION_ID_SETTINGS_LIST_ENVIRONMENTS,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/settings/environments',
    summary: 'List the project environment directory',
    request: { pathParams: settingsListEnvironmentsPathParams, csrf: false, idempotency: false },
    responses: { 200: settingsListEnvironmentsResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'rate_limited', 'authority_unavailable'],
    page: 'project.settings',
    tags: ['project-governance', 'settings'],
  },
  {
    operationId: OPERATION_ID_SETTINGS_CREATE_ENVIRONMENT,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/settings/environments',
    summary: 'Create an environment (immutable after creation; audited)',
    request: { pathParams: settingsCreateEnvironmentPathParams, body: settingsCreateEnvironmentBody, csrf: true, idempotency: true },
    responses: { 200: settingsCreateEnvironmentResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'idempotency_conflict', 'field_validation', 'rate_limited', 'authority_unavailable'],
    page: 'project.settings',
    tags: ['project-governance', 'settings'],
  },
  {
    operationId: OPERATION_ID_LIFECYCLE_ARCHIVE,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/lifecycle/archive',
    summary: 'Archive a project (stops ingestion, retains history; audited)',
    request: { pathParams: lifecycleArchiveProjectPathParams, body: lifecycleArchiveProjectBody, csrf: true, idempotency: true },
    responses: { 200: lifecycleArchiveProjectResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'state_machine_conflict', 'idempotency_conflict', 'rate_limited', 'authority_unavailable'],
    page: 'project.lifecycle',
    tags: ['project-governance', 'lifecycle'],
  },
  {
    operationId: OPERATION_ID_LIFECYCLE_RESTORE,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/lifecycle/restore',
    summary: 'Restore an archived project to active (alerts stay off; audited)',
    request: { pathParams: lifecycleRestoreProjectPathParams, body: lifecycleRestoreProjectBody, csrf: true, idempotency: true },
    responses: { 200: lifecycleRestoreProjectResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'state_machine_conflict', 'idempotency_conflict', 'rate_limited', 'authority_unavailable'],
    page: 'project.lifecycle',
    tags: ['project-governance', 'lifecycle'],
  },
  {
    operationId: OPERATION_ID_LIFECYCLE_MOVE_TO_TRASH,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/lifecycle/move-to-trash',
    summary: 'Move a project to the trash (org manager only; name + version confirmed; audited)',
    request: { pathParams: lifecycleMoveToTrashPathParams, body: lifecycleMoveToTrashBody, versioned: true, csrf: true, idempotency: true },
    responses: { 200: lifecycleMoveToTrashResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'not_found', 'business_validation', 'state_machine_conflict', 'version_conflict', 'idempotency_conflict', 'rate_limited', 'authority_unavailable'],
    page: 'project.lifecycle',
    tags: ['project-governance', 'lifecycle'],
  },
];

export interface BlockedOperation {
  readonly operationId: string;
  readonly domain: string;
  readonly reason: string;
}

export const BLOCKED_OPERATIONS: readonly BlockedOperation[] = [
  {
    operationId: 'onboardingGetProgress',
    domain: 'project-governance',
    reason: 'C1 onboarding model not formalized (G11)',
  },
  {
    operationId: 'overviewGetProjectStatus',
    domain: 'issues-and-alerts',
    reason: 'C2 overview Query not formalized (G11)',
  },
  {
    operationId: 'notificationsListAndUnread',
    domain: 'issues-and-alerts',
    reason: 'D1 notifications backend not formalized (G13)',
  },
  {
    operationId: 'policySetPlatformDefault',
    domain: 'usage-and-policy',
    reason: 'D2 PlatformAdmin authority not approved (G13)',
  },
];
