import type { RouteTargetId } from '../common/navigation.js';
import type { PaginationModel } from '../common/pagination.js';
import type { SchemaDef } from '../common/schema.js';
import { identityGetSessionResponse, OPERATION_ID_SESSION } from '../identity/session.js';
import {
  navigationGetContextResponse,
  OPERATION_ID_NAVIGATION,
} from '../identity/navigation-context.js';
import {
  identityRegisterRequest,
  identityRegisterResponse,
  OPERATION_ID_REGISTER,
} from '../identity/register.js';
import {
  identityLoginRequest,
  identityLoginResponse,
  identityLogoutResponse,
  OPERATION_ID_LOGIN,
  OPERATION_ID_LOGOUT,
} from '../identity/login.js';
import {
  identityChangePasswordRequest,
  identityChangePasswordResponse,
  identityConfirmPasswordResetRequest,
  identityConfirmPasswordResetResponse,
  identityRequestPasswordResetRequest,
  identityRequestPasswordResetResponse,
  OPERATION_ID_CHANGE_PASSWORD,
  OPERATION_ID_CONFIRM_PASSWORD_RESET,
  OPERATION_ID_REQUEST_PASSWORD_RESET,
} from '../identity/password.js';
import {
  identityConfirmEmailVerificationRequest,
  identityConfirmEmailVerificationResponse,
  OPERATION_ID_CONFIRM_EMAIL_VERIFICATION,
} from '../identity/email-verification.js';
import {
  OPERATION_ID_ACCEPT_INVITATION,
  organizationAcceptInvitationRequest,
  organizationAcceptInvitationResponse,
} from '../identity/invitation.js';
import {
  OPERATION_ID_CANCEL_ACCOUNT_DELETION,
  OPERATION_ID_CANCEL_ACCOUNT_DELETION_INTENT_LINK,
  OPERATION_ID_DELETE_ACCOUNT,
  OPERATION_ID_DELETE_ACCOUNT_INTENT_LINK,
  OPERATION_ID_DELETE_ACCOUNT_PREFLIGHT,
  OPERATION_ID_REQUEST_ACCOUNT_DELETION,
  identityCancelAccountDeletionIntentLinkPathParams,
  identityCancelAccountDeletionIntentLinkResponse,
  identityCancelAccountDeletionRequest,
  identityCancelAccountDeletionResponse,
  identityDeleteAccountIntentLinkPathParams,
  identityDeleteAccountIntentLinkResponse,
  identityDeleteAccountPreflightResponse,
  identityDeleteAccountRequest,
  identityDeleteAccountResponse,
  identityRequestAccountDeletionRequest,
  identityRequestAccountDeletionResponse,
} from '../identity/deletion.js';
import {
  OPERATION_ID_LIST_PROJECTS,
  organizationListProjectsRequest,
  organizationListProjectsResponse,
} from '../organization/workspace.js';
import {
  OPERATION_ID_CHANGE_ROLE,
  OPERATION_ID_LIST_MEMBERS,
  OPERATION_ID_REMOVE_MEMBER,
  OPERATION_ID_TRANSFER_OWNERSHIP,
  organizationChangeRolePathParams,
  organizationChangeRoleRequest,
  organizationChangeRoleResponse,
  organizationListMembersRequest,
  organizationListMembersResponse,
  organizationRemoveMemberPathParams,
  organizationRemoveMemberRequest,
  organizationRemoveMemberResponse,
  organizationTransferOwnershipPathParams,
  organizationTransferOwnershipRequest,
  organizationTransferOwnershipResponse,
} from '../organization/members.js';
import {
  OPERATION_ID_INVITE_MEMBER,
  OPERATION_ID_RESEND_INVITATION,
  OPERATION_ID_REVOKE_INVITATION,
  organizationInviteMemberPathParams,
  organizationInviteMemberRequest,
  organizationInviteMemberResponse,
  organizationResendInvitationRequest,
  organizationResendInvitationResponse,
  organizationRevokeInvitationRequest,
  organizationRevokeInvitationResponse,
} from '../organization/invitations.js';
import {
  OPERATION_ID_UPDATE_TIMEZONE,
  organizationUpdateTimezonePathParams,
  organizationUpdateTimezoneRequest,
  organizationUpdateTimezoneResponse,
} from '../organization/settings.js';
import {
  OPERATION_ID_CREATE_PROJECT,
  organizationCreateProjectPathParams,
  organizationCreateProjectRequest,
  organizationCreateProjectResponse,
} from '../project-governance/create.js';
import {
  OPERATION_ID_LIST_TRASH,
  OPERATION_ID_RESTORE_PROJECT,
  projectGovernanceListTrashRequest,
  projectGovernanceListTrashResponse,
  projectGovernanceRestoreProjectPathParams,
  projectGovernanceRestoreProjectRequest,
  projectGovernanceRestoreProjectResponse,
} from '../project-governance/trash.js';
import {
  OPERATION_ID_CREATE_PRIVATE_TOKEN,
  OPERATION_ID_LIST_PRIVATE_TOKENS,
  OPERATION_ID_REVOKE_PRIVATE_TOKEN,
  credentialsCreatePrivateTokenPathParams,
  credentialsCreatePrivateTokenRequest,
  credentialsCreatePrivateTokenResponse,
  credentialsListPrivateTokensRequest,
  credentialsListPrivateTokensResponse,
  credentialsRevokePrivateTokenRequest,
  credentialsRevokePrivateTokenResponse,
} from '../credentials/private-tokens.js';
import {
  OPERATION_ID_LIST_SECURITY_AUDIT,
  auditListSecurityAuditPathParams,
  auditListSecurityAuditQuery,
  auditListSecurityAuditResponse,
} from '../audit/security-audit.js';
import {
  OPERATION_ID_LIST_REQUEST_ENDPOINTS,
  requestsListEndpointsPathParams,
  requestsListEndpointsQuery,
  requestsListEndpointsResponse,
} from '../monitoring/request-metrics.js';
import {
  OPERATION_ID_GET_DATA_STATUS,
  diagnosticsGetDataStatusPathParams,
  diagnosticsGetDataStatusQuery,
  diagnosticsGetDataStatusResponse,
} from '../monitoring/diagnostics.js';

export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE';
export type AuthLevel = 'public' | 'intent' | 'session' | 'recent-verification';

export interface OperationDef {
  readonly operationId: string;
  readonly domain: string;
  readonly authLevel: AuthLevel;
  readonly method: HttpMethod;
  readonly path: string;
  readonly summary: string;
  readonly request?: {
    readonly pathParams?: SchemaDef;
    readonly query?: SchemaDef;
    readonly body?: SchemaDef;
    readonly idempotency?: boolean;
    readonly csrf?: boolean;
    readonly versioned?: boolean;
  };
  readonly responses: Readonly<Record<number, SchemaDef>>;
  readonly errorCodes: readonly string[];
  readonly page?: RouteTargetId;
  readonly pagination?: PaginationModel;
  readonly tags: readonly string[];
}

export const PLATFORM_OPERATIONS: readonly OperationDef[] = [
  {
    operationId: OPERATION_ID_SESSION,
    domain: 'identity',
    authLevel: 'public',
    method: 'GET',
    path: '/api/platform/v1/session',
    summary: 'Resolve the current account session projection and CSRF token',
    responses: { 200: identityGetSessionResponse },
    errorCodes: ['authentication', 'authority_unavailable'],
    page: 'workspace.home',
    tags: ['identity', 'session'],
  },
  {
    operationId: OPERATION_ID_NAVIGATION,
    domain: 'identity',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/navigation/context',
    summary: 'Resolve the authorized navigation context for the current scope',
    responses: { 200: navigationGetContextResponse },
    errorCodes: ['authentication', 'authorization', 'authority_unavailable'],
    page: 'workspace.home',
    tags: ['identity', 'navigation'],
  },
  {
    operationId: OPERATION_ID_REGISTER,
    domain: 'identity',
    authLevel: 'public',
    method: 'POST',
    path: '/api/platform/v1/auth/register',
    summary: 'Register a new account and create the personal workspace',
    request: { body: identityRegisterRequest, idempotency: true, csrf: false },
    responses: { 200: identityRegisterResponse },
    errorCodes: [
      'structural_error',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.register',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CONFIRM_EMAIL_VERIFICATION,
    domain: 'identity',
    authLevel: 'intent',
    method: 'POST',
    path: '/api/platform/v1/auth/email/confirm',
    summary: 'Confirm a pending email verification intent (intent cookie + CSRF)',
    request: { body: identityConfirmEmailVerificationRequest, idempotency: true, csrf: true },
    responses: { 200: identityConfirmEmailVerificationResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.verify-email-confirm',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_LOGIN,
    domain: 'identity',
    authLevel: 'public',
    method: 'POST',
    path: '/api/platform/v1/auth/login',
    summary: 'Authenticate an account and establish a session',
    request: { body: identityLoginRequest, idempotency: true, csrf: false },
    responses: { 200: identityLoginResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.login',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_LOGOUT,
    domain: 'identity',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/auth/logout',
    summary: 'Revoke the current session and sign out',
    request: { idempotency: false, csrf: true },
    responses: { 200: identityLogoutResponse },
    errorCodes: ['authentication', 'authorization', 'authority_unavailable'],
    page: 'auth.login',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_REQUEST_PASSWORD_RESET,
    domain: 'identity',
    authLevel: 'public',
    method: 'POST',
    path: '/api/platform/v1/auth/password/request',
    summary: 'Request a password reset email (enumeration-safe)',
    request: { body: identityRequestPasswordResetRequest, idempotency: true, csrf: false },
    responses: { 200: identityRequestPasswordResetResponse },
    errorCodes: [
      'structural_error',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.forgot-password',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CONFIRM_PASSWORD_RESET,
    domain: 'identity',
    authLevel: 'intent',
    method: 'POST',
    path: '/api/platform/v1/auth/password/confirm',
    summary: 'Confirm a password reset intent and set a new password',
    request: { body: identityConfirmPasswordResetRequest, idempotency: true, csrf: true },
    responses: { 200: identityConfirmPasswordResetResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'auth.reset-password',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CHANGE_PASSWORD,
    domain: 'identity',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/auth/password/change',
    summary: 'Change the current password and revoke all sessions',
    request: { body: identityChangePasswordRequest, idempotency: true, csrf: true },
    responses: { 200: identityChangePasswordResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_DELETE_ACCOUNT_PREFLIGHT,
    domain: 'identity',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/account/deletion/preflight',
    summary: 'Resolve the account deletion preflight projection (unique-owner blockers)',
    request: { csrf: false, idempotency: false },
    responses: { 200: identityDeleteAccountPreflightResponse },
    errorCodes: ['structural_error', 'authentication', 'authorization', 'authority_unavailable'],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_REQUEST_ACCOUNT_DELETION,
    domain: 'identity',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/account/deletion/request',
    summary: 'Send the account deletion confirmation email (creates the deletion_request intent)',
    request: { body: identityRequestAccountDeletionRequest, idempotency: true, csrf: true },
    responses: { 200: identityRequestAccountDeletionResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'state_machine_conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_DELETE_ACCOUNT_INTENT_LINK,
    domain: 'identity',
    authLevel: 'public',
    method: 'GET',
    path: '/api/platform/v1/account/deletion/intent/:token',
    summary: 'Validate the account deletion confirmation link and establish the intent cookie',
    request: {
      pathParams: identityDeleteAccountIntentLinkPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: identityDeleteAccountIntentLinkResponse },
    errorCodes: ['not_found', 'business_validation', 'authority_unavailable'],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_DELETE_ACCOUNT,
    domain: 'identity',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/account/deletion',
    summary: 'Request account deletion (dual verification + final unique-owner recheck)',
    request: { body: identityDeleteAccountRequest, idempotency: true, csrf: true },
    responses: { 200: identityDeleteAccountResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'state_machine_conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CANCEL_ACCOUNT_DELETION_INTENT_LINK,
    domain: 'identity',
    authLevel: 'public',
    method: 'GET',
    path: '/api/platform/v1/account/deletion/cancel/intent/:token',
    summary: 'Validate the deletion cancellation link and establish the intent cookie',
    request: {
      pathParams: identityCancelAccountDeletionIntentLinkPathParams,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: identityCancelAccountDeletionIntentLinkResponse },
    errorCodes: ['not_found', 'business_validation', 'authority_unavailable'],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_CANCEL_ACCOUNT_DELETION,
    domain: 'identity',
    authLevel: 'intent',
    method: 'POST',
    path: '/api/platform/v1/account/deletion/cancel',
    summary: 'Cancel an account deletion within the cooling window (intent cookie + CSRF)',
    request: { body: identityCancelAccountDeletionRequest, idempotency: true, csrf: true },
    responses: { 200: identityCancelAccountDeletionResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'state_machine_conflict',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'account.security',
    tags: ['identity', 'auth'],
  },
  {
    operationId: OPERATION_ID_ACCEPT_INVITATION,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/invitations/accept',
    summary: 'Accept an organization invitation atomically (intent cookie + CSRF)',
    request: { body: organizationAcceptInvitationRequest, idempotency: true, csrf: true },
    responses: { 200: organizationAcceptInvitationResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'invitation.accept',
    tags: ['organization', 'invitation'],
  },
  {
    operationId: OPERATION_ID_LIST_PROJECTS,
    domain: 'organization',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects',
    summary: 'List projects visible to the current account in an organization',
    request: { pathParams: organizationListProjectsRequest, csrf: false, idempotency: false },
    responses: { 200: organizationListProjectsResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'workspace.home',
    tags: ['organization', 'workspace'],
  },
  {
    operationId: OPERATION_ID_CREATE_PROJECT,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/projects',
    summary: 'Atomically create a project with default environment and client key (owner/admin)',
    request: {
      pathParams: organizationCreateProjectPathParams,
      body: organizationCreateProjectRequest,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: organizationCreateProjectResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.project-create',
    tags: ['project-governance', 'workspace'],
  },
  {
    operationId: OPERATION_ID_LIST_MEMBERS,
    domain: 'organization',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/members',
    summary: 'List organization members with masked emails',
    request: { pathParams: organizationListMembersRequest, csrf: false, idempotency: false },
    responses: { 200: organizationListMembersResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'members'],
  },
  {
    operationId: OPERATION_ID_INVITE_MEMBER,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/invitations',
    summary: 'Invite a member to an organization (atomic invite + audit)',
    request: {
      pathParams: organizationInviteMemberPathParams,
      body: organizationInviteMemberRequest,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: organizationInviteMemberResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'invitation'],
  },
  {
    operationId: OPERATION_ID_REVOKE_INVITATION,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/invitations/:invitationId/revoke',
    summary: 'Revoke a pending organization invitation',
    request: {
      pathParams: organizationRevokeInvitationRequest,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationRevokeInvitationResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'invitation'],
  },
  {
    operationId: OPERATION_ID_RESEND_INVITATION,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/invitations/:invitationId/resend',
    summary: 'Resend a pending organization invitation email',
    request: {
      pathParams: organizationResendInvitationRequest,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationResendInvitationResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'invitation'],
  },
  {
    operationId: OPERATION_ID_CHANGE_ROLE,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/members/:accountId/role',
    summary: 'Change an organization member role (never to/from owner)',
    request: {
      pathParams: organizationChangeRolePathParams,
      body: organizationChangeRoleRequest,
      versioned: true,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationChangeRoleResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'version_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'members'],
  },
  {
    operationId: OPERATION_ID_REMOVE_MEMBER,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/members/:accountId/remove',
    summary: 'Remove a member from an organization (never the last owner)',
    request: {
      pathParams: organizationRemoveMemberPathParams,
      body: organizationRemoveMemberRequest,
      versioned: true,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationRemoveMemberResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'version_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'members'],
  },
  {
    operationId: OPERATION_ID_TRANSFER_OWNERSHIP,
    domain: 'organization',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/ownership',
    summary: 'Transfer organization ownership atomically (owner invariant)',
    request: {
      pathParams: organizationTransferOwnershipPathParams,
      body: organizationTransferOwnershipRequest,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: organizationTransferOwnershipResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.members',
    tags: ['organization', 'members'],
  },
  {
    operationId: OPERATION_ID_UPDATE_TIMEZONE,
    domain: 'organization',
    authLevel: 'session',
    method: 'PATCH',
    path: '/api/platform/v1/organizations/:organizationId/settings/timezone',
    summary: 'Update the organization business timezone (versioned)',
    request: {
      pathParams: organizationUpdateTimezonePathParams,
      body: organizationUpdateTimezoneRequest,
      versioned: true,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: organizationUpdateTimezoneResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'version_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.settings',
    tags: ['organization', 'settings'],
  },
  {
    operationId: OPERATION_ID_LIST_TRASH,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/trash',
    summary: 'List recoverable trashed projects (owner/admin)',
    request: { pathParams: projectGovernanceListTrashRequest, csrf: false, idempotency: false },
    responses: { 200: projectGovernanceListTrashResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.trash',
    tags: ['project-governance', 'trash'],
  },
  {
    operationId: OPERATION_ID_RESTORE_PROJECT,
    domain: 'project-governance',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/trash/:projectId/restore',
    summary: 'Restore a trashed project within the recovery window (G10 safety rules)',
    request: {
      pathParams: projectGovernanceRestoreProjectPathParams,
      body: projectGovernanceRestoreProjectRequest,
      versioned: true,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: projectGovernanceRestoreProjectResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'state_machine_conflict',
      'idempotency_conflict',
      'version_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.trash',
    tags: ['project-governance', 'trash'],
  },
  {
    operationId: OPERATION_ID_LIST_PRIVATE_TOKENS,
    domain: 'credentials',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/private-tokens',
    summary: 'List private management tokens (metadata only, no secret)',
    request: { pathParams: credentialsListPrivateTokensRequest, csrf: false, idempotency: false },
    responses: { 200: credentialsListPrivateTokensResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.tokens',
    tags: ['credentials', 'tokens'],
  },
  {
    operationId: OPERATION_ID_CREATE_PRIVATE_TOKEN,
    domain: 'credentials',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/private-tokens',
    summary: 'Create a private management token (one-time plaintext delivery)',
    request: {
      pathParams: credentialsCreatePrivateTokenPathParams,
      body: credentialsCreatePrivateTokenRequest,
      idempotency: true,
      csrf: true,
    },
    responses: { 200: credentialsCreatePrivateTokenResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'idempotency_conflict',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.tokens',
    tags: ['credentials', 'tokens'],
  },
  {
    operationId: OPERATION_ID_REVOKE_PRIVATE_TOKEN,
    domain: 'credentials',
    authLevel: 'session',
    method: 'POST',
    path: '/api/platform/v1/organizations/:organizationId/private-tokens/:tokenId/revoke',
    summary: 'Irreversibly revoke a private management token',
    request: {
      pathParams: credentialsRevokePrivateTokenRequest,
      csrf: true,
      idempotency: false,
    },
    responses: { 200: credentialsRevokePrivateTokenResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'business_validation',
      'field_validation',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.tokens',
    tags: ['credentials', 'tokens'],
  },
  {
    operationId: OPERATION_ID_LIST_SECURITY_AUDIT,
    domain: 'audit',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/audit',
    summary: 'List the security audit timeline (redacted summaries)',
    request: {
      pathParams: auditListSecurityAuditPathParams,
      query: auditListSecurityAuditQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: auditListSecurityAuditResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'organization.audit',
    tags: ['audit', 'security'],
  },
  {
    operationId: OPERATION_ID_LIST_REQUEST_ENDPOINTS,
    domain: 'monitoring-projections',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/requests',
    summary: 'List request endpoint metric projections for a project time window',
    request: {
      pathParams: requestsListEndpointsPathParams,
      query: requestsListEndpointsQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: requestsListEndpointsResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.requests',
    tags: ['monitoring', 'requests'],
  },
  {
    operationId: OPERATION_ID_GET_DATA_STATUS,
    domain: 'monitoring-projections',
    authLevel: 'session',
    method: 'GET',
    path: '/api/platform/v1/organizations/:organizationId/projects/:projectId/data-status',
    summary: 'Resolve the ingestion data-status diagnosis projection for a project (safe summaries)',
    request: {
      pathParams: diagnosticsGetDataStatusPathParams,
      query: diagnosticsGetDataStatusQuery,
      csrf: false,
      idempotency: false,
    },
    responses: { 200: diagnosticsGetDataStatusResponse },
    errorCodes: [
      'structural_error',
      'authentication',
      'authorization',
      'not_found',
      'rate_limited',
      'authority_unavailable',
    ],
    page: 'project.data-status',
    tags: ['monitoring', 'diagnostics'],
  },
];

export interface BlockedOperation {
  readonly operationId: string;
  readonly domain: string;
  readonly reason: string;
}

export const BLOCKED_OPERATIONS: readonly BlockedOperation[] = [
  {
    operationId: 'usageGetSummary',
    domain: 'usage-and-policy',
    reason: 'B5 usage module absent (G10/G11)',
  },
  {
    operationId: 'onboardingGetProgress',
    domain: 'project-governance',
    reason: 'C1 onboarding model not formalized (G11)',
  },
  {
    operationId: 'overviewGetProjectStatus',
    domain: 'issues-and-alerts',
    reason: 'C2 overview Query not formalized (G11)',
  },
  {
    operationId: 'issuesListIssues',
    domain: 'issues-and-alerts',
    reason: 'C3 processing-store Query contract absent (G11)',
  },
  {
    operationId: 'issuesGetIssueDetail',
    domain: 'issues-and-alerts',
    reason: 'C4 processing-store Query contract absent (G11)',
  },
  {
    operationId: 'performanceListPages',
    domain: 'monitoring-projections',
    reason: 'C6 performance metric Query absent (G11)',
  },
  {
    operationId: 'releasesListReleases',
    domain: 'releases',
    reason: 'C8 releases model not formalized (G12)',
  },
  {
    operationId: 'sourceMapsListFiles',
    domain: 'releases',
    reason: 'C9 Source Map/object store not formalized (G12)',
  },
  {
    operationId: 'alertsListRulesAndInstances',
    domain: 'issues-and-alerts',
    reason: 'C10 alert model not formalized (G12)',
  },
  {
    operationId: 'alertsCreateRule',
    domain: 'issues-and-alerts',
    reason: 'C11 alert rule model not formalized (G12)',
  },
  {
    operationId: 'alertsGetInstanceDetail',
    domain: 'issues-and-alerts',
    reason: 'C12 alert instance Query absent (G12)',
  },
  {
    operationId: 'accessListEffectiveMembers',
    domain: 'project-governance',
    reason: 'C13 access projection not formalized (G12)',
  },
  {
    operationId: 'credentialsListClientKeys',
    domain: 'credentials',
    reason: 'C14 client-key management not formalized (G12)',
  },
  {
    operationId: 'settingsGetProject',
    domain: 'project-governance',
    reason: 'C15 settings model not formalized (G12)',
  },
  {
    operationId: 'lifecycleArchiveProject',
    domain: 'project-governance',
    reason: 'C16 lifecycle model not formalized (G12)',
  },
  {
    operationId: 'notificationsListAndUnread',
    domain: 'issues-and-alerts',
    reason: 'D1 notifications backend not formalized (G13)',
  },
  {
    operationId: 'policySetPlatformDefault',
    domain: 'usage-and-policy',
    reason: 'D2 PlatformAdmin authority not approved (G13)',
  },
];
